### ISSUE TITLE
Poor quality outputs when building from repo

### ISSUE THREAD

**Issue by intrepidlemon** [ProfFan/Snap2LaTeX#6]
I was trying to use the feature that was just merged, for copying automatically to the clipboard: https://github.com/ProfFan/Snap2LaTeX/pull/5

I was able to build locally on my mac, but for some reason, the quality of the model output is very poor when built locally, often including "Object object", possibly a javascript serialization bug? 

I also see an additional option about using Float16, so I suspect there may be some changes to the model on the most recent branches, but I'm not entirely sure. 

Thank you for any help here. (I was also unable to get github actions to work to build this).

**Comment by ProfFan** [comment]
I think you did not allow the app to capture the screen, if you actually built locally you will need to manually add your locally built app in `Security`

**Comment by ProfFan** [comment]
@intrepidlemon 0.5.0 is released, please update and see if it works

**Comment by intrepidlemon** [comment]
It works great! Thank you so much!

**Comment by intrepidlemon** [comment]
Also, for anyone else trying to build, I think @ProfFan is correct about not having sufficient permissions to take a screenshot. I think I had two copies of the same app (one built and one downloaded) may have been confusing to the mac permissions panel. Not really sure how to fix that though, since a second separate application did not show up in the panel after I built it.
